name: backend_cidades
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  sqflite: ^2.0.0
  json_annotation: ^4.9.0
  build_runner: ^2.4.9
  http: ^1.2.1
  shelf: ^1.4.1
  shelf_router: ^1.1.4


dev_dependencies:
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0

